from __future__ import annotations

from pathlib import Path


class TPF2LuaWriter:
    MOD_ID = "osm_map_studio"

    def __init__(
        self,
        name="OSM Map Studio",
        description="OpenStreetMap import for Transport Fever 2",
        author="TPF3-Map-Studio",
    ):
        self.name = str(name)
        self.description = str(description)
        self.author = str(author)

    def write(self, tpf2_data, output_path):
        output_path = Path(output_path)
        mod_dir = (
            output_path.parent / output_path.stem
            if output_path.suffix.lower() == ".con"
            else output_path
        )

        script_dir = mod_dir / "res" / "scripts" / self.MOD_ID
        script_dir.mkdir(parents=True, exist_ok=True)

        (mod_dir / "mod.lua").write_text(
            self.build_mod_lua(), encoding="utf-8"
        )
        (script_dir / "osmdata.lua").write_text(
            self.build_osmdata_lua(tpf2_data), encoding="utf-8"
        )
        (script_dir / "main.lua").write_text(
            self.build_main_lua(), encoding="utf-8"
        )

        return mod_dir

    def build_mod_lua(self):
        return "\n".join([
            "function data()",
            "    return {",
            "        info = {",
            f'            name = "{self._escape(self.name)}",',
            f'            description = "{self._escape(self.description)}",',
            "            authors = {",
            "                {",
            f'                    name = "{self._escape(self.author)}",',
            '                    role = "CREATOR",',
            "                },",
            "            },",
            "            minorVersion = 0,",
            '            severityAdd = "WARNING",',
            '            severityRemove = "WARNING",',
            '            tags = {"Script Mod", "Misc"},',
            "        },",
            "",
            "        -- TPF2 calls this after the mod is loaded.",
            "        -- The importer is started automatically; no console global is needed.",
            "        postRunFn = function(settings)",
            '            local importer = require "osm_map_studio.main"',
            "            importer.start()",
            "        end,",
            "    }",
            "end",
            "",
        ])

    def build_osmdata_lua(self, data):
        lines = [
            "-- Generated by TPF3-Map-Studio",
            "return {",
            f"    version = {int(data.get('version', 2))},",
            "    nodes = {",
        ]

        for node_id in sorted(data.get("nodes", {}), key=str):
            pos = data["nodes"][node_id].get("pos", [0.0, 0.0])
            lines += [
                f"        [{self._lua_value(str(node_id))}] = {{",
                f"            pos = {self._vec2(pos)},",
                "        },",
            ]

        lines += ["    },", "    edges = {"]

        for edge_id in sorted(data.get("edges", {}), key=str):
            edge = data["edges"][edge_id]
            lines += [
                f"        [{self._lua_value(str(edge_id))}] = {{",
                f"            id = {self._lua_value(edge.get('id', edge_id))},",
                f"            node0 = {self._lua_value(edge.get('node0'))},",
                f"            node1 = {self._lua_value(edge.get('node1'))},",
                f"            tangent0 = {self._vec3(edge.get('tangent0'))},",
                f"            tangent1 = {self._vec3(edge.get('tangent1'))},",
            ]

            if edge.get("track") is not None:
                track = edge["track"]
                lines += [
                    "            track = {",
                    f"                type = {self._lua_value(track.get('type', 'rail'))},",
                    f"                electrified = {'true' if track.get('electrified') else 'false'},",
                    "            },",
                ]
            else:
                lines += [
                    "            street = {",
                    '                type = "road",',
                    "                oneway = false,",
                    "            },",
                ]

            lines.append("        },")

        lines += ["    },", "}", ""]
        return "\n".join(lines)

    def build_main_lua(self):
        return r'''local data = require "osm_map_studio.osmdata"

local M = {
    data = data,
    running = false,
    stop = false,
    index = 0,
    success = 0,
    failed = 0,
    edge_ids = {},
}

local STREET_TYPE = "standard/town_medium_new.lua"
local TRACK_TYPE = "standard.lua"

local function find_node(pos)
    local entities = game.interface.getEntities(
        { pos = pos, radius = 3 },
        { type = "BASE_NODE" }
    )

    local best = nil
    local best_d2 = 1e-6

    for _, id in pairs(entities) do
        local c = api.engine.getComponent(
            id,
            api.type.ComponentType.BASE_NODE
        )

        if c then
            local dx = pos[1] - c.position.x
            local dy = pos[2] - c.position.y
            local d2 = dx * dx + dy * dy

            if d2 <= best_d2 then
                best = id
                best_d2 = d2
            end
        end
    end

    return best
end

local function make_node(id, pos)
    local n = api.type.NodeAndEntity.new()
    n.entity = id

    n.comp.position = api.type.Vec3f.new(
        pos[1],
        pos[2],
        pos[3] or 0
    )

    return n
end

local function make_edge(id, edge, n0, n1)
    local e = api.type.SegmentAndEntity.new()
    e.entity = id

    local owner = api.type.PlayerOwned.new()
    owner.player = game.interface.getPlayer()
    e.playerOwned = owner

    e.comp.node0 = n0
    e.comp.node1 = n1

    e.comp.tangent0 = api.type.Vec3f.new(
        edge.tangent0[1],
        edge.tangent0[2],
        edge.tangent0[3] or 0
    )

    e.comp.tangent1 = api.type.Vec3f.new(
        edge.tangent1[1],
        edge.tangent1[2],
        edge.tangent1[3] or 0
    )

    if edge.track then
        e.type = 1
        e.trackEdge.trackType =
            api.res.trackTypeRep.find(TRACK_TYPE)
        e.trackEdge.catenary =
            edge.track.electrified == true

    elseif edge.street then
        e.type = 0
        e.streetEdge.streetType =
            api.res.streetTypeRep.find(STREET_TYPE)
        e.streetEdge.hasBus = false
        e.streetEdge.tramTrackType = 0

    else
        return nil
    end

    return e
end

local function build_current()
    local edge_id = M.edge_ids[M.index]

    if not edge_id then
        M.running = false

        print(
            "OSM Map Studio fertig. OK="
            .. tostring(M.success)
            .. " FAIL="
            .. tostring(M.failed)
        )

        return
    end

    if M.stop then
        M.running = false
        print("OSM Map Studio gestoppt.")
        return
    end

    local edge = data.edges[edge_id]

    if not edge then
        M.failed = M.failed + 1
        M.index = M.index + 1
        build_current()
        return
    end

    local d0 = data.nodes[edge.node0]
    local d1 = data.nodes[edge.node1]

    if not d0 or not d1 then
        M.failed = M.failed + 1
        M.index = M.index + 1
        build_current()
        return
    end

    local existing0 = find_node(d0.pos)
    local existing1 = find_node(d1.pos)

    local proposal = api.type.SimpleProposal.new()
    local n0 = existing0
    local n1 = existing1

    -- TPF2 requires negative entity IDs to be local to this proposal.
    -- Added segments must use -1, -2, ... and added nodes must use
    -- subsequent negative IDs. Large arbitrary negative IDs can trigger
    -- an internal assertion/crash in the construction builder.
    local next_node_id = -2

    if not existing0 then
        n0 = next_node_id
        next_node_id = next_node_id - 1

        proposal.streetProposal.nodesToAdd:add(
            make_node(n0, d0.pos)
        )
    end

    if not existing1 then
        n1 = next_node_id

        proposal.streetProposal.nodesToAdd:add(
            make_node(n1, d1.pos)
        )
    end

    if n0 == n1 then
        M.failed = M.failed + 1
        M.index = M.index + 1
        build_current()
        return
    end

    local segment = make_edge(
        -1,
        edge,
        n0,
        n1
    )

    if not segment then
        M.failed = M.failed + 1
        M.index = M.index + 1
        build_current()
        return
    end

    proposal.streetProposal.edgesToAdd:add(segment)

    local command = api.cmd.make.buildProposal(
        proposal,
        nil,
        true
    )

    api.cmd.sendCommand(
        command,
        function(result, success)
            if success then
                M.success = M.success + 1
            else
                M.failed = M.failed + 1
                print(
                    "Edge fehlgeschlagen: "
                    .. tostring(edge_id)
                )
            end

            M.index = M.index + 1

            if M.index % 100 == 0 then
                print(
                    "OSM Import "
                    .. tostring(M.index)
                    .. " / "
                    .. tostring(#M.edge_ids)
                    .. " | OK="
                    .. tostring(M.success)
                    .. " FAIL="
                    .. tostring(M.failed)
                )
            end

            build_current()
        end
    )
end

function M.start()
    if M.running then
        print("OSM Map Studio läuft bereits.")
        return
    end

    M.edge_ids = {}

    for id, _ in pairs(data.edges) do
        table.insert(M.edge_ids, id)
    end

    table.sort(
        M.edge_ids,
        function(a, b)
            return tostring(a) < tostring(b)
        end
    )

    M.running = true
    M.stop = false
    M.index = 1
    M.success = 0
    M.failed = 0

    print("OSM Map Studio startet.")
    print("Edges: " .. tostring(#M.edge_ids))

    build_current()
end

function M.stop_import()
    M.stop = true
    print("OSM Map Studio: Stop angefordert.")
end

function M.status()
    print(
        "OSM Map Studio: "
        .. tostring(M.index)
        .. " / "
        .. tostring(#M.edge_ids)
        .. " OK="
        .. tostring(M.success)
        .. " FAIL="
        .. tostring(M.failed)
    )
end

return M
'''
    @staticmethod
    def _vec2(value):
        if not value or len(value) < 2:
            return "{ 0.0, 0.0 }"
        return (
            "{ "
            + TPF2LuaWriter._lua_number(value[0])
            + ", "
            + TPF2LuaWriter._lua_number(value[1])
            + " }"
        )

    @staticmethod
    def _vec3(value):
        if not value or len(value) < 2:
            return "{ 0.0, 0.0, 0.0 }"
        z = value[2] if len(value) > 2 else 0.0
        return (
            "{ "
            + TPF2LuaWriter._lua_number(value[0])
            + ", "
            + TPF2LuaWriter._lua_number(value[1])
            + ", "
            + TPF2LuaWriter._lua_number(z)
            + " }"
        )

    @staticmethod
    def _lua_value(value):
        if value is None:
            return "nil"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return TPF2LuaWriter._lua_number(value)
        return '"' + TPF2LuaWriter._escape(value) + '"'

    @staticmethod
    def _lua_number(value):
        value = float(value)
        if value != value or value == 0.0:
            return "0.0"
        return f"{value:.6f}".rstrip("0").rstrip(".")

    @staticmethod
    def _escape(value):
        return (
            str(value)
            .replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )
